### ISSUE TITLE
All in one image

### ISSUE THREAD

**Issue by AlexTryHarder** [rybbit-io/rybbit#146]
Can we please have all in one docker image (without caddy).

especialy with build and dockerfile is not always suitable approach for deployment.

**Comment by smileBeda** [comment]
Not necessarily an "all in one" image since things like postgres and simile should not be bundled into one huge image, but, the need of cloning the GitHub repo and build locally is something that needs to be worked on.

When using docker at its full potential, we just need a well documented `.env` and `docker-compose.yml`
This should be all that is required.

And I agree, the additional caddy part should be removed in its entirety. I will make maintenance and documentation for the maintainers easier too, and self hosting people will know how to pull up a proxy on their own (and rarely will want something like caddy embedded in the image anyway)

**Comment by goldflag** [comment]
> Not necessarily an "all in one" image since things like postgres and simile should not be bundled into one huge image, but, the need of cloning the GitHub repo and build locally is something that needs to be worked on.
> 
> When using docker at its full potential, we just need a well documented `.env` and `docker-compose.yml` This should be all that is required.
> 
> And I agree, the additional caddy part should be removed in its entirety. I will make maintenance and documentation for the maintainers easier too, and self hosting people will know how to pull up a proxy on their own (and rarely will want something like caddy embedded in the image anyway)

If anyone wants to improve the self hosting setup I am totally happy to take contributions. I mostly a frontend dev so I was that familiar with the ways self hosters deploy stuff.

**Comment by smileBeda** [comment]
Here's what I do:
1. Create `docker-compose.yml` file with contents as below
2. Create `.env` as below
3. Create a NPM entry where you put a entry for `rybbit_client` pointing to port 3002
4. Create a NPM Custom Location rewrite like below to fix #135 (might not be needed after anymore)
```
location /api/ {
    rewrite ^/api(/.*)$ $1 break;
    proxy_pass http://rybbit_backend:3001;
}
```

**DOCKER COMPOSE**
- note, `npm_proxy` is an external network on which your NPM has to be too
- note, this is still in testing but works well on my end so far
- note, there is NO need to clone the entire repo, just use what steps above shown
- note, ports for clickhouse will be removed at some point (entirely possible) so that no ports are exposed due to docker overwrites of iptables. This is WIP
- note, I removed clickhouse config, as I found the settings in the repo here where mostly what is default anyway, but I will eventually add them back in,
```
services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:25.4.2
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
#      - ./clickhouse_config:/etc/clickhouse-server/config.d
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-analytics}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-frog}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal

  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-frog}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-frog}
      - POSTGRES_DB=${POSTGRES_DB:-analytics}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

  rybbit_backend:
    image: ghcr.io/rybbit-io/rybbit-backend:${IMAGE_TAG:-latest}
    container_name: rybbit_backend
    ports:
      - "${HOST_BACKEND_PORT}"
    environment:
      - NODE_ENV=production
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-analytics}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-frog}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-analytics}
      - POSTGRES_USER=${POSTGRES_USER:-frog}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-frog}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BASE_URL=${BASE_URL}
      - DISABLE_SIGNUP=${DISABLE_SIGNUP}
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_started
    restart: unless-stopped
    networks:
      - internal
      - npm_proxy

  rybbit_client:
    image: ghcr.io/rybbit-io/rybbit-client:${IMAGE_TAG:-latest}
    container_name: rybbit_client
    ports:
      - "${HOST_CLIENT_PORT}"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=${BASE_URL}
    depends_on:
      - rybbit_backend
    restart: unless-stopped
    networks:
      - internal
      - npm_proxy

networks:
  internal:
    driver: bridge
  npm_proxy:
    external: true
```

**ENV**
```
DOMAIN_NAME=your-domain.tld
BASE_URL=https://your-domain.tld
BETTER_AUTH_SECRET=WHATEVER_UNIQUE_ENOUGH_VALUE
DISABLE_SIGNUP=false
HOST_BACKEND_PORT=3001
HOST_CLIENT_PORT=3002
```

_nothing else is needed_. 
You do not need to clone the repo, maintain setup shells, etc.
