### ISSUE TITLE
Self-Hosted Instance Tracking Issue

### ISSUE THREAD

**Issue by ilkersigirci** [rybbit-io/rybbit#378]
First of all, thank you for this open source app, just love it. I am trying to self host the latest version (currently 1.1.0) using `traefik`. I have added script to my website. The `script.js` endpoint is successfully fetched in my website as you can see in the SS below,  but the rybbit dashboard still doesn't see this. I have added my `docker-compose` file for anyone interested. Thanks in advance

PS: I have tried to use the cloud instance. In there, everything works perfectly for my website. Hence, I think there is an issue for my self-hosted instance.

Backend logs
![Image](https://github.com/user-attachments/assets/7783d568-a1df-4fca-bc4a-668b4f737bb5)

My docker-compose
```yml
services:
  rybbit-clickhouse:
    image: clickhouse/clickhouse-server:25.4.2
    container_name: rybbit-clickhouse
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - monitoring
      - rybbit
    networks:
      - t3_proxy
    expose:
      - "8123"
      - "9000"
    volumes:
      - $DOCKERDIR/appdata/rybbit/clickhouse:/var/lib/clickhouse
      - $CONFIGDIR/rybbit/clickhouse:/etc/clickhouse-server/config.d:ro
    environment:
      - TZ=$TZ
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-analytics}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-frog}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s

  rybbit-postgres:
    image: postgres:17.4
    container_name: rybbit-postgres
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - monitoring
      - rybbit
    networks:
      - t3_proxy
    expose:
      - "5432"
    volumes:
      - $DOCKERDIR/appdata/rybbit/postgres:/var/lib/postgresql/data
    environment:
      # - TZ=$TZ # Doesn't work
      - POSTGRES_USER=${POSTGRES_USER:-frog}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-frog}
      - POSTGRES_DB=${POSTGRES_DB:-analytics}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s

  rybbit-backend:
    image: ghcr.io/rybbit-io/rybbit-backend:${IMAGE_TAG:-latest}
    container_name: rybbit-backend
    restart: $MAINTENANCE_RESTART_POLICY
    depends_on:
      rybbit-clickhouse:
        condition: service_healthy
      rybbit-postgres:
        condition: service_started
    profiles:
      - monitoring
      - rybbit
    networks:
      - t3_proxy
    environment:
      - TZ=$TZ
      - NODE_ENV=production
      - CLICKHOUSE_HOST=http://rybbit-clickhouse:8123
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-analytics}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-frog}
      - POSTGRES_HOST=rybbit-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-analytics}
      - POSTGRES_USER=${POSTGRES_USER:-frog}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-frog}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-my_random_auth_secret}
      - BASE_URL=https://analytics.$DOMAINNAME
      - DISABLE_SIGNUP=${DISABLE_SIGNUP:-true}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3001/api/health"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.rybbit-api-rtr.entrypoints=websecure"
      - "traefik.http.routers.rybbit-api-rtr.rule=Host(`analytics.$DOMAINNAME`) && Pathprefix(`/api/`)"
      ## HTTP Services
      - "traefik.http.routers.rybbit-api-rtr.service=rybbit-api-svc"
      - "traefik.http.services.rybbit-api-svc.loadbalancer.server.port=3001"

  rybbit-client:
    image: ghcr.io/rybbit-io/rybbit-client:${IMAGE_TAG:-latest}
    container_name: rybbit-client
    profiles:
      - monitoring
      - rybbit
    networks:
      - t3_proxy
    environment:
      - TZ=$TZ
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=https://analytics.$DOMAINNAME
      - NEXT_PUBLIC_DISABLE_SIGNUP=${DISABLE_SIGNUP:-true}
    depends_on:
      - rybbit-backend
    restart: $MAINTENANCE_RESTART_POLICY
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.rybbit-rtr.entrypoints=websecure"
      - "traefik.http.routers.rybbit-rtr.rule=Host(`analytics.$DOMAINNAME`)"
      ## HTTP Services
      - "traefik.http.routers.rybbit-rtr.service=rybbit-svc"
      - "traefik.http.services.rybbit-svc.loadbalancer.server.port=3002"
```
