### ISSUE TITLE
How to setup non-interactively?

### ISSUE THREAD

**Issue by elibroftw** [rybbit-io/rybbit#409]
I'm trying to add this into an ansible playbook. Right now I'll have to use the expect module in ansible, but would be nice if I didn't have to run the setup script locally first.

**Comment by elibroftw** [comment]
<details><summary>Ansible playbook so far</summary>

```yml
- name: Deploy Rybbit
  hosts: elijahlopez_ca_1
  tasks:
    - name: Clone or pull Rybbit repository
      ansible.builtin.git:
        repo: https://github.com/rybbit-io/rybbit.git
        dest: /opt/rybbit
        update: yes
      notify: Deploy Rybbit

    - name: Make setup.sh executable
      ansible.builtin.file:
        path: /opt/rybbit/setup.sh
        state: file
        mode: u+x

    - name: Run Rybbit setup script
      ansible.builtin.command: /opt/rybbit/setup.sh ryb.elijahlopez.ca --no-webserver
      args:
        creates: /opt/rybbit/.setup_done

    - name: Create sentinel file
      ansible.builtin.file:
        path: /opt/rybbit/.setup_done
        state: touch
        mode: '0644'

  handlers:
  - name: Deploy Rybbit
    community.docker.docker_compose_v2:
        project_src: /opt/rybbit
        services:
          - backend
          - client
          - clickhouse
          - postgres
        state: present
        started: true
```

</details>

Error

```
fatal: [elijahlopez_ca_1]: FAILED! => {"changed": true, "cmd": ["/opt/rybbit/setup.sh", "ryb.elijahlopez.ca", 
"--no-webserver"], "delta": "0:00:00.202987", "end": "2025-06-16 03:02:50.352355", "msg": 
"non-zero return code", "rc": 1, "start": "2025-06-16 03:02:50.149368", "stderr": "no configuration file 
provided: not found", "stderr_lines": ["no configuration file provided: not found"], "stdout": "Creating .env 
file...\n.env file created successfully with domain ryb.elijahlopez.ca.\nCaddy webserver is disabled. You'll need 
to set up your own webserver.\nThe backend service will be available on port 3001 and the client on port 
3002.\nBuilding and starting Docker services...", "stdout_lines": ["Creating .env file...", ".env file created 
successfully with domain ryb.elijahlopez.ca.", "Caddy webserver is disabled. You'll need to set up your own 
webserver.", "The backend service will be available on port 3001 and the client on port 3002.", "Building and 
starting Docker services..."]}
```
